name: Publishing docker image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: molecule_test_container
        with:
          images: ghcr.io/inc4/molecule_test_container

      - uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.molecule_test_container.outputs.tags }}
          labels: ${{ steps.molecule_test_container.labels }}
